apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire-mgmt-api.fullname" . }}-db
  labels:
    {{- include "spire-mgmt-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mysql.user | quote }}
  password: {{ .Values.mysql.password | quote }}
