{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "site-agent.serviceAccountName" . }}
  labels:
    {{- include "site-agent.labels" . | nindent 4 }}
{{- end }}
